name: Build GDS using OpenLANE and sky130 PDK

on: [push]
jobs:
  build-openlane:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout subservient
        uses: actions/checkout@v4
      - name: Build with Openlane
        uses: librecores/ci-fusesoc-action@migrate-dockerized
        with:
          core: serv
          target: sky130
          tool: openlane
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: serv.gds
          path: /home/runner/work/serv/serv/build/serv_1.2.1/sky130-openlane/gds/serv_synth_wrapper.gds
